language: node_js
node_js:
  - node
  - lts/*
  - 10
  - 8
deploy:
  provider: npm
  email: mail@geraintwhite.co.uk
  api_key:
    secure: tsAebUuPC66fldqlhcSQzJilVrgWfrqH51ZPqQK+4O60Y0dpg/mEhLn5PxR0kiOxoSrki5vi109Hl0TMXOTzRQXXY+hVbGlFk82Sisuw/MW69p6S0OvTIOxObnAh97m/yj2BUgcHaD1pmsSDwfDClhK/WVwpZChV82fm6fJWQqnPeuzaZyaIwwScXUnsSDmppBwa/Opuv1XNs5SEd37aZUF882cQjJ8syuF0MEdv90iIPFFOB72reu7tMqGAI8IoJDU/ddi4vdPL40QgMevpGyGKoZq5sOEnhlZNyChV+77Ah/dyl1UFRQ31w9QpRimb5lkWWoEOvPzr3oNXLTf5nToE8UnhHoLgcKskZlS3CEIhV/AlyXIOOHJXDFpSdPmwxODf+2Vgr9ox3a89cIHFPXvhYiuycg9mtJXBnDIhXxbfT/9fqm55SmVOgI5FnK5CFH+djwhsgRh0U8pNQ2fPJBkbPmOeJVhqK/2o8cFIH4yeGN9DbRVyKA6uE9pCPmYVHeVC+hpD0gSLp5kJRYby/krUxo0ADPpQgox0L0ytOHzcmXAykeMF7vDJHrlQAhQmMvVIYp5Oe6+Bn9TKuR0MTZlv+rsv/cSsVLtznrN66g+VuptJ6I2vC4LYG86oCrnlO1ZEID4qNNj8DWK1el2zasXzZgD1+gojzxL008m3lCo=
  on:
    tags: true
    repo: geraintwhite/async-tools
