language: node_js
node_js:
  - 10
  - 8
  - 6
  - 4
deploy:
  provider: npm
  email: geraintwhite@gmail.com
  api_key:
    secure: Pfkqi2kGjdgRgKjI3RKkz7pmFawilkaqvTs5ssM86cNhVNcCWMa6Wpqdm+U0pvHyvGxnJJH4i8NRLXc/jCdFZdZKYA9+1FOnyntjbWvz6IvpDfIJYLexdmP7JQvhkZ0OzlSKEFbwB9FTC3fThW3UgoGGjG/HfWIQ2a6ClVJQQIXRFTu6+749h2ra3owDhLTNcByhnVfJ3kRGG6x/NMuy0o0KRLbPYpLe4xY+yjqP/1Xx03wSwJFepI/BbKEnS+WYqxoXLjzGlliRJLlqKALSoCDnpokshShYYwwhT7ONY8GUP2s3fDCzyccdjL4XsSQ6mxAJalrWT682PZEzCtmOD7R7QUsIHwDJVahISThmexrSTZ5AzW3rU9am5nqm/lWCB9tbtSTFENVal1gK/l7BqSPBGIt2lcwEWvP9Po0X/OsKNldbYYesljnb0kZaLX5tPu2pK/b42KUu5amtsW5ZYWjBNp/BOh+PtpgBNB0eOwdQTmNc5d7ik4puxNLEfiq8kMN/u4c7hGFPMyxF10i4pg2qd+A5yyKBIjomOdB+5c5X8qCD+ztQT3SGdYhT3/XR9H34ixA3z7D/q+TL9JxP1ZEQrY5IqCGNq0hormhnXbOpxPeOg2XjuIaKZTpOPWD1F9+axsIHsYT9BsgPy/lHS/xCRJ+F1ReTLemO3ROEcPc=
  on:
    tags: true
    repo: grit96/async-tools
